### ISSUE TITLE
cypher-result-element not show node's id when identity=0

### ISSUE THREAD

**Issue by abstract-liu** [TuGraph-family/tugraph-web#1]
When I query cypher like "match (n) where id(n)=0 return n",
node with identity 0 will not show its id detail, like screenshot attached.
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/45623625/189026168-19e23196-bb6d-42c1-8495-ba37190e60bc.png">

Related code are below in file 「cypher-result-element-detail.vue」: 
<img width="978" alt="image" src="https://user-images.githubusercontent.com/45623625/189026876-6941b615-b058-44f6-ac2f-98253393df77.png">

I wonder if this is a bug or feature, and the code meaning here.

Thanks a lot for your reply.

**Comment by KingSkyLi** [comment]
Yes, this is a bug. Due to an error in the logic of obtaining the node ID, the result obtained here is undefined. We will fix it in a later feature.

**Comment by abstract-liu** [comment]
Okay, hope to see the next exciting release.
And I wonder if outside contributors are not able to get involved in right now?
Thank for your reply
